import { Injectable } from '@angular/core';
import { vehicle } from 'src/app/Classes/vehicle';

@Injectable({
  providedIn: 'root'
})
export class VehicleService {

  constructor() { }

  getVehiclebyId(id: number):vehicle{
    return this.getVehicles().find(vehicle => vehicle.id == id)!;
  }
    

  getVehicles():vehicle[]{
    return [
      {
          "id": 0,
          "brand": "Toyota",
          "condition": "Used",
          "fuel": "Diesel",
          "engine_capacity": "1900cc",
          "steering": "Hydraulic Power",
          "kms_driven": 100000,
          "model": "Prado",
          "price": 2100000,
          "registered_city": "Karachi",
          "transaction_type": "Cash",
          "year": 1997,
          "rating": 5,
          "image": "../../assets/Images/toyota_prado_1997.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },

        {
          "id": 1,
          "brand": "Suzuki",
          "condition": "Used",
          "fuel": "Petrol",
          "engine_capacity": "1000cc",
          "steering": "Non-Power Manual",
          "kms_driven": 100000,
          "model": "Bolan",
          "price": 380000,
          "registered_city": "Lahore",
          "transaction_type": "Cash",
          "year": 2006,
          "rating": 4,
          "image": "../../assets/Images/suzuki_bolan_2006.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },

        {
          "id": 2,
          "brand": "Suzuki",
          "condition": "Used",
          "fuel": "Petrol",
          "engine_capacity": "1000cc",
          "steering": "Non-Power Manual",
          "kms_driven": 94000,
          "model": "Alto",
          "price": 535000,
          "registered_city": "Lahore",
          "transaction_type": "Cash",
          "year": 2010,
          "rating": 4,
          "image": "../../assets/Images/suzuki_alto_2010.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 3,
          "brand": "Toyota",
          "condition": "Used",
          "fuel": "Petrol",
          "engine_capacity": "1300cc",
          "steering": "Hydraulic Power",
          "kms_driven": 100000,
          "model": "Corolla XLI",
          "price": 1430000,
          "registered_city": "Karachi",
          "transaction_type": "Cash",
          "year": 2013,
          "rating": 5,
          "image": "../../assets/Images/toyota_corolla_xli_2013.jpeg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
    
        },
        {
          "id": 4,
          "brand": "Toyota",
          "condition": "Used",
          "fuel": "Petrol",
          "engine_capacity": "1600cc",
          "steering": "Hydraulic Power",
          "kms_driven": 80000,
          "model": "Corrolla Altis",
          "price": 1620000,
          "registered_city": "Peshawar",
          "transaction_type": "Cash",
          "year": 2012,
          "rating": 5,
          "image": "../../assets/Images/corolla_altis_2012.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },      
        {
          "id": 5,
          "brand": "Suzuki",
          "condition": "New",
          "fuel": "CNG",
          "engine_capacity": "1000cc",
          "steering": "Non-Power Manual",
          "kms_driven": 65000,
          "model": "Cultus VXR",
          "price": 450000,
          "registered_city": "Karachi",
          "transaction_type": "Cash",
          "year": 2006,
          "rating": 5,
          "image": "../../assets/Images/suzuki_cultus_vxr_2006.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 6,
          "brand": "Toyota",
          "condition": "New",
          "fuel": "Petrol",
          "engine_capacity": "1600cc",
          "steering": "Hydraulic Power",
          "kms_driven": 10241,
          "model": "Corrolla Altis",
          "price": 2900000,
          "registered_city": "Lahore",
          "transaction_type": "Cash",
          "year": 2017,
          "rating": 4,
          "image": "../../assets/Images/toyota-corolla-altis-2017.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 7,
          "brand": "Suzuki",
          "condition": "Used",
          "fuel": "CNG",
          "engine_capacity": "1000cc",
          "steering": "Non Power Manual",
          "kms_driven": 83000,
          "model": "Alto",
          "price": 490000,
          "registered_city": "Islamabad",
          "transaction_type": "Cash",
          "year": 2009,
          "rating": 3,
          "image": "../../assets/Images/suzuki-alto-2009.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 8,
          "brand": "Honda",
          "condition": "Used",
          "fuel": "Petrol",
          "engine_capacity": "1329cc",
          "steering": "Non-Power Manual",
          "kms_driven": 115323,
          "model": "Civic VTi",
          "price": 480000,
          "registered_city": "Karachi",
          "transaction_type": "Cash",
          "year": 2006,
          "rating": 4,
          "image": "../../assets/Images/honda_civic_vti_2007.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 9,
          "brand": "Suzuki",
          "condition": "Used",
          "fuel": "CNG",
          "engine_capacity": "1329cc",
          "steering": "Non Power Manual",
          "kms_driven": 123,
          "model": "Khyber",
          "price": 230000,
          "registered_city": "Karachi",
          "transaction_type": "Cash",
          "rating": 5,
          "year": 1994,
          "image": "../../assets/Images/suzuki_khyber_1994.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 10,
          "brand": "Suzuki",
          "condition": "Used",
          "fuel": "CNG",
          "engine_capacity": "1328cc",
          "steering": "Non-Power Manual",
          "kms_driven": 73000,
          "model": "Liana",
          "price": 535000,
          "registered_city": "Peshawar",
          "transaction_type": "Cash",
          "rating": 5,
          "year": 2006,
          "image": "../../assets/Images/suzuki_liana_2006.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 11,
          "brand": "Toyota",
          "condition": "Used",
          "fuel": "Petrol",
          "engine_capacity": "1000cc",
          "steering": "Hydraulic Power",
          "kms_driven": 78000,
          "model": "Passo",
          "price": 770000,
          "registered_city": "Lahore",
          "transaction_type": "Cash",
          "rating": 3,
          "year": 2006,
          "image": "../../assets/Images/toyota_passo_2006.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        },
        {
          "id": 12,
          "brand": "Honda",
          "condition": "Used",
          "fuel": "Petrol",
          "engine_capacity": "1590cc",
          "steering": "Non-Power Manual",
          "kms_driven": 1,
          "model": "Civic Prosmetic",
          "price": 490000,
          "registered_city": "Islamabad",
          "transaction_type": "Cash",
          "rating": 3,
          "year": 1997,
          "image": "../../assets/Images/honda_civic_1997.jpg",
          "seller_name": "Shop Auto",
          "seller_image": "../../assets/Images/seller_logo.jpg",
          "seller_comments": ["This car is almost brand new, it is in mint condition and working perfectly.", "Took this car out for a test drive, very enjoyable experience."]
        }     
    ]
  }
}


// "../../assets/Images/corolla_altis_2012.jpg",
// "../../assets/Images/honda_civic_1997.jpg",
// "../../assets/Images/honda_civic_2021_red.jpg",
// "../../assets/Images/honda_civic_vti_2007.jpg",
// "../../assets/Images/suzuki_alto_2010.jpg",
// "../../assets/Images/suzuki_khyber_1994.jpg",
// "../../assets/Images/suzuki_liana_2006.jpg",
// "../../assets/Images/suzuki-alto-2009.jpg",
// "../../assets/Images/toyota_prado_1997.jpg",
// "../../assets/Images/suzuki_liana_2006.jpg",
// "../../assets/Images/suzuki_cultus_vxr_2006.jpg",
// "../../assets/Images/toyota_passo_2006.jpg",
// "../../assets/Images/toyota_corolla_xli_2013.jpeg",
// "../../assets/Images/toyota-corolla-altis-2017.jpg",